fs = import('fs')
fs.copyfile('test.obj')
fs.copyfile('test2.obj')
fs.copyfile('test3.obj')
fs.copyfile('test4.obj')
fs.copyfile('test5.obj')
fs.copyfile('testlegacy.obj')
fs.copyfile('testnew.obj')
fs.copyfile('fouranimals.obj')
fs.copyfile('badgerbard.obj')
fs.copyfile('cube.obj')
fs.copyfile('uvsphere.obj')
fs.copyfile('icosphere.obj')
fs.copyfile('uvsphere-norm.obj')
fs.copyfile('uvsphere-weight-norm.obj')
fs.copyfile('uvsphere-high-res.obj')